// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTxzwu1j5zfKWbi6eSs4mTy6Uxcqv3o9U',
    appId: '1:138088718871:web:cc125d2cd7593302d37252',
    messagingSenderId: '138088718871',
    projectId: 'vehicales-18608',
    authDomain: 'vehicales-18608.firebaseapp.com',
    storageBucket: 'vehicales-18608.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3752g-tMjN1vTirA3Zhp6tlG5fQ1wB30',
    appId: '1:138088718871:android:5e0f7dcd98fa9a86d37252',
    messagingSenderId: '138088718871',
    projectId: 'vehicales-18608',
    storageBucket: 'vehicales-18608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuY62AMpd15zx8n3wvJM8sk8EbOAgQ4ic',
    appId: '1:138088718871:ios:dbacd6a233519c67d37252',
    messagingSenderId: '138088718871',
    projectId: 'vehicales-18608',
    storageBucket: 'vehicales-18608.appspot.com',
    iosBundleId: 'com.example.vehicalesDetails',
  );
}
